services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev  # Use the development stage for hot reloading, change to prod to run production build
    ports:
      - "3000:3000"  # Map port 3000 for React development server
    volumes:
      - ./frontend:/app  # Mount the local frontend code to the container for live updates
      - /app/node_modules  # Prevent node_modules from being overwritten by local system
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes hot-reloading issues in Docker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Mount the backend folder to the container for hot reloading
      - /app/node_modules  # Prevents overriding node_modules
    env_file:
      - ./backend/.env
    command: ["nodemon", "app.js"]  # Run nodemon for hot reloading
